### ISSUE TITLE
unclear description

### ISSUE THREAD

**Issue by yndajas** [learn-co-curriculum/js-advanced-functions-collection-processing-methods-family-tree#6]
"findIndex: Find the first element that satisfies the callback's index" - this is unclear language. The meaning is "[the first element that satisfies the callback]'s index" or "the index that belongs to [the first element that satisfies the callback]", but there are too many words in the [] part, leading to a reading of needing to satisfy the callback's index, which makes no sense.

It would be much clearer to say "Find the index of the first element that satisfies the callback"

**Comment by ihollander** [comment]
Thanks for your suggestion! This has been updated.
